# VJson document generator jazzy settings

copyright: Copyright 2016-2017 rien@balancingrock.nl
author: Balancingrock
module: VJson
hide_documentation_coverage: true
xcodebuild_arguments: [-target, VJson]
github_url: https://github.com/Balancingrock/VJson
output: ~/Documents/Websites/swiftfire.nl/projects/vjson/reference
clean: true
theme: fullwidth
