# SwifterJSON document generator jazzy settings

copyright: Copyright 2016-2017 Rien van der Lugt
author: Rien van der Lugt
module: SwifterJSON
hide_documentation_coverage: true
xcodebuild_arguments: [-target, SwifterJSON]
github_url: https://github.com/Balancingrock/SwifterJSON
output: ~/Documents/Websites/sf/projects/swifterjson/reference
clean: true
theme: fullwidth
